'use client'
import { useEffect,useState,useCallback } from 'react'
import { useRouter } from 'next/navigation'
import { supabase,VAPID_PUBLIC_KEY } from '../../lib/supabaseClient'
import NavBar from './NavBar'

const HABITS=[['agua','💧','Agua','Bebi agua ao longo do dia'],['alimentacao_consciente','🥗','Alimentacao','Fiz uma refeicao com atencao'],['movimento','👟','Movimento','Movimentei meu corpo'],['sono_regular','☾','Sono','Cuidei do meu horario de sono'],['gentileza','♡','Autoestima','Falei comigo com gentileza']]
const PILARES=[['🍃','Alimentacao','Escolhas conscientes, sem proibicoes.'],['🏃','Movimento','Um corpo ativo do seu jeito.'],['🌙','Sono','Descanso tambem e progresso.'],['♡','Autoestima','Gentileza muda a jornada.']]
const MENSAGENS=['Voce nao precisa ser perfeita. So precisa ser constante.','Cada pequeno passo te leva mais longe.','Cuidar de voce tambem cabe nos dias corridos.','Seu ritmo ainda e progresso.','Hoje e uma nova chance de escolher com carinho.','Constancia e voltar, mesmo depois de uma pausa.','Celebre o que seu corpo tornou possivel hoje.','Mudancas leves tambem constroem resultados duradouros.','A melhor rotina e aquela que acolhe a sua vida.','Um gesto de cuidado pode mudar o tom do seu dia.','Nao subestime a forca de comecar pequeno.','Seu bem-estar nao precisa esperar pela segunda-feira.']
const empty={agua:false,alimentacao_consciente:false,movimento:false,sono_regular:false,gentileza:false,nota_do_dia:''}
function todayISO(){const d=new Date(),tz=d.getTimezoneOffset();return new Date(d.getTime()-tz*60000).toISOString().slice(0,10)}
function urlBase64ToUint8Array(s){const p='='.repeat((4-s.length%4)%4),raw=atob((s+p).replace(/-/g,'+').replace(/_/g,'/'));return Uint8Array.from([...raw].map(c=>c.charCodeAt(0)))}

export default function AppPage(){
 const router=useRouter(),[loading,setLoading]=useState(true),[profile,setProfile]=useState(null),[entry,setEntry]=useState(empty),[saving,setSaving]=useState(false),[pushState,setPushState]=useState('checking'),[novoPeso,setNovoPeso]=useState(''),[openPillar,setOpenPillar]=useState(null)
 const checkPushState=useCallback(async()=>{if(!('Notification'in window)||!('serviceWorker'in navigator)||!('PushManager'in window)){setPushState('unsupported');return}if(Notification.permission==='denied'){setPushState('denied');return}try{const r=await navigator.serviceWorker.ready;setPushState(await r.pushManager.getSubscription()?'subscribed':'default')}catch{setPushState('default')}},[])
 const load=useCallback(async()=>{const{data:s}=await supabase.auth.getSession();if(!s.session){router.replace('/login');return}const uid=s.session.user.id,{data:p}=await supabase.from('profiles').select('*').eq('id',uid).single();if(p&&!p.onboarding_completo){router.replace('/app/perfil');return}if(p&&!p.onboarding_completed){router.replace('/app/onboarding');return}setProfile(p);setNovoPeso(String(p?.peso_atual_kg??''));const{data:e}=await supabase.from('diario_entries').select('*').eq('user_id',uid).eq('entry_date',todayISO()).maybeSingle();setEntry(e?{...empty,...e}:empty);setLoading(false);checkPushState()},[router,checkPushState])
 useEffect(()=>{load()},[load])
 async function saveEntry(next){setSaving(true);const{data:s}=await supabase.auth.getSession();await supabase.from('diario_entries').upsert({user_id:s.session.user.id,entry_date:todayISO(),...next},{onConflict:'user_id,entry_date'});setSaving(false)}
 async function toggle(key){const next={...entry,[key]:!entry[key]};setEntry(next);await saveEntry(next)}
 async function atualizarPeso(){const valor=parseFloat(novoPeso);if(!valor||valor<=0)return;const{data:s}=await supabase.auth.getSession(),{data:p}=await supabase.from('profiles').update({peso_atual_kg:valor}).eq('id',s.session.user.id).select().single();if(p)setProfile(p)}
 async function ativarLembretes(){setPushState('requesting');try{if(await Notification.requestPermission()!=='granted'){setPushState('denied');return}const reg=await navigator.serviceWorker.ready;let sub=await reg.pushManager.getSubscription();if(!sub)sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:urlBase64ToUint8Array(VAPID_PUBLIC_KEY)});const j=sub.toJSON(),{data:s}=await supabase.auth.getSession();await supabase.from('push_subscriptions').upsert({user_id:s.session.user.id,endpoint:j.endpoint,p256dh:j.keys.p256dh,auth:j.keys.auth},{onConflict:'endpoint'});setPushState('subscribed')}catch{setPushState('default')}}
 async function signOut(){await supabase.auth.signOut();router.replace('/login')}
 if(loading)return <div className="loading">Preparando seu dia...</div>
 const trialEnd=profile?.trial_ends_at?new Date(profile.trial_ends_at):null,daysLeft=trialEnd?Math.max(0,Math.ceil((trialEnd-new Date())/86400000)):0,isTrial=profile?.subscription_status==='trial'
 if(isTrial&&trialEnd<new Date())return <div className="container"><div className="card" style={{textAlign:'center',marginTop:60}}><span className="pillar-icon">🍃</span><h1>Seu teste terminou</h1><p className="muted">Continue sua jornada com o Metodo LEVE.</p><a className="btn" href="https://pay.kiwify.com.br/SEU-LINK-DE-ASSINATURA">Conhecer planos</a><button className="link-btn" onClick={signOut}>Sair</button></div><NavBar/></div>
 const ini=profile?.peso_inicial_kg,atual=profile?.peso_atual_kg,meta=profile?.peso_meta_kg,perdido=ini&&atual?Math.max(0,ini-atual):0,pct=ini&&atual&&meta&&ini>meta?Math.min(100,Math.max(0,perdido/(ini-meta)*100)):0,done=HABITS.filter(([k])=>entry[k]).length,msg=MENSAGENS[new Date().getDate()%MENSAGENS.length]
 const dates=[-2,-1,0,1].map(n=>{const d=new Date();d.setDate(d.getDate()+n);return{n,label:n===0?'Hoje':n===-1?'Ontem':n===1?'Amanha':d.toLocaleDateString('pt-BR',{weekday:'short'}),day:d.getDate()}})
 return <div className="container">
  <header className="header"><div><span className="eyebrow">Seu momento LEVE</span><h1>Ola, {profile?.nome?.split(' ')[0]||'bem-vinda'} 👋</h1></div><button className="icon-btn" aria-label="Notificacoes" onClick={ativarLembretes}>♢</button></header>
  {isTrial&&<section className="card premium-card"><span className="pill">SEU PERIODO DE TESTE</span><h2>{daysLeft?`Restam ${daysLeft} dias`:'Ultimo dia do seu teste'}</h2><p style={{marginTop:0}}>Explore tudo o que preparamos para voce.</p><div className="progress-track"><div className="progress-fill" style={{width:`${((7-daysLeft)/7)*100}%`}}/></div><a className="btn btn-light" href="https://pay.kiwify.com.br/SEU-LINK-DE-ASSINATURA" style={{marginTop:16}}>Conhecer planos</a></section>}
  <section className="card"><div className="card-title"><div><span className="eyebrow">Meta do dia</span><h2 style={{margin:'5px 0 0'}}>Seu hoje, com leveza</h2></div><span className="pill">{done}/5</span></div><div className="progress-track"><div className="progress-fill" style={{width:`${done*20}%`}}/></div><p className="muted" style={{fontSize:13}}>Complete uma pequena acao de cada vez.</p></section>
  {meta&&<section className="card"><div className="card-title"><div><span className="eyebrow">Meu progresso</span><h2 style={{margin:'5px 0 0'}}>Voce esta avancando</h2></div><div className="progress-ring" style={{background:`conic-gradient(var(--success) ${pct}%,var(--green-2) 0)`}}><span>{pct.toFixed(0)}%</span></div></div><div className="metric-grid"><div className="metric"><small className="muted">Peso perdido</small><strong>{perdido.toFixed(1)} kg</strong></div><div className="metric"><small className="muted">Peso atual</small><strong>{atual} kg</strong></div><div className="metric"><small className="muted">Meta final</small><strong>{meta} kg</strong></div><div className="metric"><small className="muted">Atualizar</small><div style={{display:'flex',gap:5,marginTop:5}}><input aria-label="Novo peso" type="number" step=".1" value={novoPeso} onChange={e=>setNovoPeso(e.target.value)} style={{margin:0,padding:8,minWidth:0}}/><button className="status-btn" onClick={atualizarPeso}>OK</button></div></div></div><p className="muted" style={{fontSize:13,marginBottom:0}}>Cada pequeno passo te leva mais longe.</p></section>}
  <section className="card"><span className="eyebrow">Mensagem do dia</span><p className="quote">“{msg}”</p><span className="muted" style={{fontSize:12}}>Um lembrete para guardar com voce.</span></section>
  {pushState==='default'&&<section className="card"><div className="card-title"><div><span className="eyebrow">Lembretes gentis</span><h3 style={{margin:'5px 0 0'}}>Receba pequenos lembretes para cuidar de você ao longo do dia.</h3></div><span>🔔</span></div><p className="muted" style={{fontSize:12}}>Você poderá desativá-los quando quiser.</p><button className="btn btn-secondary" onClick={ativarLembretes}>Ativar lembretes</button></section>}
  <section><div className="card-title"><div><span className="eyebrow">Equilibrio</span><h2 style={{margin:'5px 0 0'}}>Os quatro pilares</h2></div></div><div className="pillar-grid">{PILARES.map((p,i)=><button className="pillar" key={p[1]} onClick={()=>setOpenPillar(openPillar===i?null:i)}><span className="pillar-icon">{p[0]}</span><strong>{p[1]}</strong><small>{openPillar===i?p[2]:'Toque para conhecer'}</small></button>)}</div></section>
  <section className="card" style={{marginTop:16}}><div className="card-title"><div><span className="eyebrow">Diario LEVE</span><h2 style={{margin:'5px 0 0'}}>Como foi seu dia?</h2></div><div className="streak">🔥 1 dia</div></div><div className="date-strip">{dates.map(d=><div className={`date-chip ${d.n===0?'active':''}`} key={d.n}><small>{d.label}</small><b>{d.day}</b></div>)}</div>{HABITS.map(([k,icon,title,desc])=><label className={`check-row ${entry[k]?'done':''}`} key={k}><span className="habit-icon">{icon}</span><span><strong>{title}</strong><br/><small className="muted">{desc}</small></span><input type="checkbox" checked={!!entry[k]} onChange={()=>toggle(k)}/></label>)}<textarea placeholder="Escreva algo sobre o seu dia..." value={entry.nota_do_dia} onChange={e=>setEntry({...entry,nota_do_dia:e.target.value})} onBlur={()=>saveEntry(entry)} rows="4" style={{marginTop:16}}/>{saving&&<small className="muted">Salvando automaticamente...</small>}</section>
  <button className="link-btn" style={{width:'100%'}} onClick={signOut}>Sair da conta</button><NavBar/>
 </div>
}
