'use client'
import {useCallback,useEffect,useState} from 'react'
import {useRouter} from 'next/navigation'
import {supabase} from '../../../lib/supabaseClient'
import NavBar from '../NavBar'
const HABITS=[['agua','💧','Bebi agua ao longo do dia','Meta: 2 litros'],['alimentacao_consciente','🥗','Comi uma refeicao com atencao plena',''],['movimento','👟','Me movimentei por pelo menos 20 minutos',''],['sono_regular','🌙','Dormi em horario regular',''],['gentileza','❤️','Falei comigo mesma com gentileza','']]
const empty={agua:false,alimentacao_consciente:false,movimento:false,sono_regular:false,gentileza:false,nota_do_dia:''}
function iso(d=new Date()){const z=d.getTimezoneOffset();return new Date(d-z*60000).toISOString().slice(0,10)}
export default function DiarioPage(){
 const router=useRouter(),[loading,setLoading]=useState(true),[entry,setEntry]=useState(empty),[saving,setSaving]=useState(false)
 const load=useCallback(async()=>{const{data:s}=await supabase.auth.getSession();if(!s.session){router.replace('/login');return}const{data:e}=await supabase.from('diario_entries').select('*').eq('user_id',s.session.user.id).eq('entry_date',iso()).maybeSingle();setEntry(e?{...empty,...e}:empty);setLoading(false)},[router])
 useEffect(()=>{load()},[load])
 useEffect(()=>{if(loading)return;const focus=new URLSearchParams(window.location.search).get('focus'),id=focus==='water'?'habit-water':focus==='reflection'?'daily-reflection':null;if(id){const el=document.getElementById(id);el?.scrollIntoView({behavior:'smooth',block:'center'});el?.classList.add('notification-focus');setTimeout(()=>el?.classList.remove('notification-focus'),3500)}},[loading])
 async function save(next){setSaving(true);const{data:s}=await supabase.auth.getSession();await supabase.from('diario_entries').upsert({user_id:s.session.user.id,entry_date:iso(),...next},{onConflict:'user_id,entry_date'});setSaving(false)}
 function toggle(k){const n={...entry,[k]:!entry[k]};setEntry(n);save(n)}
 if(loading)return <div className="loading">Abrindo seu diario...</div>
 const now=new Date(),dates=Array.from({length:7},(_,i)=>{const d=new Date(now);d.setDate(now.getDate()+i-3);return d}),done=HABITS.filter(([k])=>entry[k]).length
 return <div className="container"><header className="header"><div><span className="eyebrow">Seu momento</span><h1>Diario LEVE</h1></div><button className="icon-btn">▣</button></header><div className="date-strip">{dates.map(d=><div className={`date-chip ${iso(d)===iso()?'active':''}`} key={iso(d)}><small>{d.toLocaleDateString('pt-BR',{weekday:'short'}).slice(0,1).toUpperCase()}</small><b>{d.getDate()}</b></div>)}</div><div className="card-title"><div><h3 style={{margin:0}}>{now.toLocaleDateString('pt-BR',{weekday:'long',day:'numeric',month:'long'})}</h3><small className="muted">Foque em voce hoje.</small></div><span style={{fontSize:24}}>♡</span></div><section className="card">{HABITS.map(([k,icon,title,sub])=><label id={k==='agua'?'habit-water':undefined} className={`check-row ${entry[k]?'done':''}`} key={k}><span className="habit-icon">{icon}</span><span>{title}{sub&&<><br/><small className="muted">{sub}</small></>}</span><input type="checkbox" checked={!!entry[k]} onChange={()=>toggle(k)}/></label>)}</section><section id="daily-reflection" className="card"><label style={{fontSize:13,fontWeight:600}}>Como foi o seu dia?</label><textarea placeholder="Escreva aqui..." rows="5" value={entry.nota_do_dia} onChange={e=>setEntry({...entry,nota_do_dia:e.target.value})} onBlur={()=>save(entry)} style={{border:0,padding:'14px 0',boxShadow:'none'}}/>{saving&&<small className="muted">Salvando...</small>}</section><section className="card" style={{display:'flex',alignItems:'center',gap:15}}><span style={{fontSize:38}}>🔥</span><div><small className="muted">Sua sequencia</small><h2 style={{margin:'2px 0'}}>{done===5?'1 dia':'Continue hoje'}</h2><small className="muted">Cada check conta.</small></div></section><div style={{display:'flex',gap:8,justifyContent:'center'}}>{HABITS.map(([k])=><span key={k} style={{width:32,height:32,borderRadius:'50%',display:'grid',placeItems:'center',background:entry[k]?'var(--success)':'#fff',color:entry[k]?'#fff':'var(--line)'}}>✓</span>)}</div><NavBar/></div>
}
