'use client'
import {useEffect,useState} from 'react'
import {useRouter} from 'next/navigation'
import {supabase} from '../../../lib/supabaseClient'
import NavBar from '../NavBar'
const BADGES=[['🌱','Primeiro dia',1],['🔥','3 dias',3],['✨','7 dias',7],['🏅','14 dias',14],['🎯','21 dias',21]]
export default function ProgressoPage(){
 const router=useRouter(),[loading,setLoading]=useState(true),[profile,setProfile]=useState(null),[entries,setEntries]=useState([]),[tab,setTab]=useState('Geral'),[exerciseCount,setExerciseCount]=useState(0),[favCount,setFavCount]=useState(0)
 useEffect(()=>{setExerciseCount(JSON.parse(localStorage.getItem('leve_exercicios')||'[]').length);setFavCount(JSON.parse(localStorage.getItem('leve_favoritas')||'[]').length);(async()=>{const{data:s}=await supabase.auth.getSession();if(!s.session){router.replace('/login');return}const uid=s.session.user.id;const[{data:p},{data:e}]=await Promise.all([supabase.from('profiles').select('*').eq('id',uid).single(),supabase.from('diario_entries').select('*').eq('user_id',uid).order('entry_date',{ascending:true}).limit(30)]);setProfile(p);setEntries(e||[]);setLoading(false)})()},[router])
 if(loading)return <div className="loading">Reunindo suas conquistas...</div>
 const ini=profile?.peso_inicial_kg||0,atual=profile?.peso_atual_kg||ini,meta=profile?.peso_meta_kg||0,lost=Math.max(0,ini-atual),habitTotal=entries.reduce((n,e)=>n+['agua','alimentacao_consciente','movimento','sono_regular','gentileza'].filter(k=>e[k]).length,0),streak=entries.length
 const values=entries.slice(-10).map((e,i)=>({x:i,y:['agua','alimentacao_consciente','movimento','sono_regular','gentileza'].filter(k=>e[k]).length,date:e.entry_date})),max=Math.max(1,...values.map(v=>v.y))
 return <div className="container"><header className="header"><div><span className="eyebrow">Sua evolucao</span><h1>Meu progresso</h1><p className="muted" style={{fontSize:13}}>Veja o quanto voce ja construiu.</p></div><span className="icon-btn">↗</span></header><div className="tabs">{['Geral','Peso','Habitos','Medidas'].map(t=><div key={t} className={`tab ${tab===t?'active':''}`} onClick={()=>setTab(t)}>{t}</div>)}</div>
 <div className="metric-grid"><div className="metric"><small className="muted">Peso perdido</small><strong>{lost.toFixed(1)} kg</strong></div><div className="metric"><small className="muted">Dias registrados</small><strong>{entries.length}</strong></div><div className="metric"><small className="muted">Habitos feitos</small><strong>{habitTotal}</strong></div><div className="metric"><small className="muted">Movimentos</small><strong>{exerciseCount}</strong></div></div>
 {(tab==='Geral'||tab==='Habitos')&&<section className="card" style={{marginTop:16}}><div className="card-title"><div><span className="eyebrow">Ultimos dias</span><h2 style={{margin:'5px 0 0'}}>Ritmo dos habitos</h2></div></div>{values.length?<div style={{height:170,display:'flex',alignItems:'end',gap:8}}>{values.map(v=><div key={v.date} style={{flex:1,textAlign:'center'}}><div title={`${v.y} habitos`} style={{height:`${Math.max(8,v.y/max*130)}px`,background:'var(--success)',borderRadius:'9px 9px 3px 3px'}}/><small className="muted" style={{fontSize:9}}>{v.date.slice(8)}</small></div>)}</div>:<p className="muted">Seus registros aparecerao aqui conforme voce preencher o diario.</p>}</section>}
 {(tab==='Geral'||tab==='Peso')&&<section className="card"><span className="eyebrow">Jornada de peso</span><h2>{atual} kg agora</h2><div className="progress-track"><div className="progress-fill" style={{width:`${ini>meta?Math.max(0,Math.min(100,lost/(ini-meta)*100)):0}%`}}/></div><div style={{display:'flex',justifyContent:'space-between',marginTop:9}}><small className="muted">Inicio {ini} kg</small><small className="muted">Meta {meta||'—'} kg</small></div></section>}
 {tab==='Medidas'&&<section className="card"><span className="eyebrow">Em breve</span><h2>Medidas corporais</h2><p className="muted">Esta area ficara pronta quando houver campos de medidas no seu perfil. Nenhuma alteracao foi feita no banco.</p></section>}
 <section><div className="card-title"><div><span className="eyebrow">Pequenas vitorias</span><h2 style={{margin:'5px 0 0'}}>Minhas conquistas</h2></div></div><div className="pillar-grid">{BADGES.map(([icon,name,need])=><div className="pillar" style={{opacity:streak>=need?1:.45}} key={name}><span className="pillar-icon">{icon}</span><strong>{name}</strong><small>{streak>=need?'Conquistado':'Continue avançando'}</small></div>)}<div className="pillar" style={{opacity:favCount?1:.45}}><span className="pillar-icon">🥗</span><strong>Primeira receita</strong><small>{favCount?'Conquistado':'Favorite uma receita'}</small></div></div></section><NavBar/></div>
}
