export const RECIPES = [
  {
    id: 'omelete',
    title: 'Omelete Verde da Manha Leve',
    meal: 'Cafe da manha',
    time: '10 min',
    kcal: '~220 kcal',
    image: '/receitas/r1-omelete-real.webp',
    contains: [],
    ingredientes: ['2 ovos', 'Um punhado de espinafre', 'Meio tomate picado', '1 fatia de pao integral'],
    preparo: 'Bata os ovos, refogue o espinafre e o tomate, misture com os ovos e cozinhe em fogo baixo. Sirva com a fatia de pao integral.',
  },
  {
    id: 'bowl',
    title: 'Bowl Colorido do Almoco Leve',
    meal: 'Almoco',
    time: '20 min',
    kcal: '~420 kcal',
    image: '/receitas/r2-bowl-real.webp',
    contains: [],
    ingredientes: ['Arroz integral', 'Frango grelhado', 'Brocolis', 'Cenoura ralada', 'Meio abacate'],
    preparo: 'Monte o prato em camadas coloridas: arroz, frango, brocolis, cenoura e abacate. Tempere com azeite e limao.',
  },
  {
    id: 'sopa',
    title: 'Sopa Aconchego da Noite Leve',
    meal: 'Jantar',
    time: '25 min',
    kcal: '~280 kcal',
    image: '/receitas/r3-sopa-real.webp',
    contains: [],
    ingredientes: ['Abobora', 'Cenoura', 'Cebola', 'Gengibre', 'Frango desfiado'],
    preparo: 'Cozinhe os legumes, bata ate virar um creme e finalize com o frango desfiado por cima.',
  },
  {
    id: 'iogurte',
    title: 'Iogurte Power da Tarde Leve',
    meal: 'Lanche',
    time: '5 min',
    kcal: '~180 kcal',
    image: '/receitas/r4-iogurte-real.webp',
    contains: ['lactose'],
    ingredientes: ['Iogurte natural', 'Aveia', 'Canela', 'Morango picado'],
    preparo: 'Misture tudo em uma tigela e finalize com canela por cima.',
  },
  {
    id: 'doce',
    title: 'Doce Sem Culpa Leve',
    meal: 'Sobremesa',
    time: '15 min',
    kcal: '~150 kcal',
    image: '/receitas/r5-doce-real.webp',
    contains: ['amendoim'],
    ingredientes: ['Banana amassada', 'Aveia', 'Canela', '1 colher de pasta de amendoim'],
    preparo: 'Misture os ingredientes e leve ao forno por 15 minutos, ate dourar.',
  },
]

export const CONTAINS_LABEL = {
  lactose: 'Contem leite/lactose',
  amendoim: 'Contem amendoim',
}
