-- Método LEVE: onboarding persistente e infraestrutura idempotente de notificações.
alter table public.profiles
  add column if not exists onboarding_completed boolean not null default false,
  add column if not exists onboarding_completed_at timestamptz,
  add column if not exists welcome_notification_scheduled_at timestamptz,
  add column if not exists welcome_notification_sent_at timestamptz;

create table if not exists public.notification_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  notification_id text not null,
  category text not null,
  target_url text not null default '/app',
  scheduled_at timestamptz,
  sent_at timestamptz,
  opened_at timestamptz,
  error_code text,
  created_at timestamptz not null default now()
);

create unique index if not exists notification_history_welcome_once
  on public.notification_history(user_id, notification_id)
  where notification_id = 'welcome-01';
create index if not exists notification_history_recent
  on public.notification_history(user_id, sent_at desc);

create table if not exists public.exercise_completions (
  user_id uuid not null references auth.users(id) on delete cascade,
  exercise_day smallint not null check (exercise_day between 1 and 21),
  completed_at timestamptz not null default now(),
  primary key(user_id, exercise_day)
);
alter table public.exercise_completions enable row level security;
drop policy if exists "Users manage own exercise completions" on public.exercise_completions;
create policy "Users manage own exercise completions" on public.exercise_completions
  for all using(auth.uid()=user_id) with check(auth.uid()=user_id);

alter table public.notification_history enable row level security;
drop policy if exists "Users read own notification history" on public.notification_history;
create policy "Users read own notification history" on public.notification_history
  for select using (auth.uid() = user_id);

create or replace function public.schedule_welcome_on_profile_created()
returns trigger language plpgsql security definer set search_path=public as $$
declare due_at timestamptz := now() + interval '10 minutes';
begin
  update profiles set welcome_notification_scheduled_at=due_at where id=new.id;
  insert into notification_history(user_id,notification_id,category,target_url,scheduled_at)
    values(new.id,'welcome-01','welcome','/app',due_at) on conflict do nothing;
  return new;
end $$;
drop trigger if exists schedule_welcome_after_profile_insert on public.profiles;
create trigger schedule_welcome_after_profile_insert
  after insert on public.profiles for each row execute function public.schedule_welcome_on_profile_created();

create or replace function public.schedule_welcome_notification()
returns timestamptz
language plpgsql security definer set search_path=public
as $$
declare due_at timestamptz;
begin
  if auth.uid() is null then raise exception 'not_authenticated'; end if;
  select welcome_notification_scheduled_at into due_at from profiles where id=auth.uid() for update;
  if due_at is null then
    due_at := now() + interval '10 minutes';
    update profiles set welcome_notification_scheduled_at=due_at where id=auth.uid();
    insert into notification_history(user_id,notification_id,category,target_url,scheduled_at)
      values(auth.uid(),'welcome-01','welcome','/app',due_at)
      on conflict do nothing;
  end if;
  return due_at;
end $$;
grant execute on function public.schedule_welcome_notification() to authenticated;

create or replace function public.mark_notification_opened(p_notification_id text)
returns void language sql security definer set search_path=public as $$
  update notification_history set opened_at=coalesce(opened_at,now())
  where user_id=auth.uid() and notification_id=p_notification_id;
$$;
grant execute on function public.mark_notification_opened(text) to authenticated;

-- Execute após publicar a Edge Function process-notifications e habilitar pg_cron/pg_net:
-- select cron.schedule('leve-process-notifications','* * * * *',
--   $$select net.http_post(url:='https://tizvuzrhfjkovhhtxswc.supabase.co/functions/v1/process-notifications',
--     headers:=jsonb_build_object('Authorization','Bearer ' || current_setting('app.settings.cron_secret')),
--     body:='{}'::jsonb);$$);
